apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-eval-app
  labels:
    app: argo-eval-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-eval-app
  template:
    metadata:
      labels:
        app: argo-eval-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: argo-eval-app
          image: veeranarni/hotstar:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
