apiVersion: v1
kind: Service
metadata:
  name: argo-eval-app
  labels:
    app: argo-eval-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: argo-eval-app
